const base = "https://api.unsplash.com";
const id = "/?client_id=";
const key = "BrsjeRi6VzsaSFCdZQ-65IbZDeithdic2GYnpKdNLqU";
const photos = "/photos";
const search = "/search";
const perpage = "&per_page=20";
const query = "&query=";
const page = "&page=";
const order = "&order_by=";
const old = "oldest";
const latest = "latest";
const popular = "popular";

const api = base + photos + id + key + perpage;
const searchapi = base + search + photos + id + key + perpage;

const assetIcon = "assets/image/icon.png";
const assetTransparen = "assets/image/icon_trans.png";
const assetIcon512 = "assets/image/dazzle512.png";

const downloadHiveBox = "com.dazzleapp.dazzle_downloadbox";
const favoriteHiveBox = "com.dazzleapp.dazzle_favoritebox";
const favoriteSearchHiveBox = "com.dazzleapp.dazzle_favoriteSbox";

const wallpaperTitle = "Wallpaper";
const downloadTitle = "Download";
const favoriteTitle = "Favorite";
const fontFamily = "Ubuntu";
const setScreenAs = "Set wallpaper as :";
const homeScreen = "Home Screen";
const lockScreen = "Lock Screen";
const bothScreen = "Home & Lock Screen";
const shareTEXT = 'Share';
const setAs = "SET AS";
const successMessage = "Download Success";
const downloadedMessage = "Image Downloaded";
const doneMessage = "Done";
const homeMessage = "Apply on Home Screen";
const lockMessage = "Apply on Lock Screen";
const bothMessage = "Apply on Both Screen";
const searchText = "Search";
const downloadText = "Download";
const favoriteText = "Favorite";
const homeText = "Home";
const searchResult = "No Wallpaper Found";
const todayText = "Latest";
const popularText = "Trending";
const oOldestText = "Oldest";
const emptyText = "Empty";
const mobileConnected = "Mobile Data Connected";
const wifiConnected = "Wifi Connected";
const noConnection = "No Internet Connection";
const double elevationNo = 2;
const int snakbarDuration = 2;
const int nativeAdsCount = 5;
const double nativeAdsHEIGHT = 170;
